#include <stdio.h> 
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <libgen.h>
#include <sys/types.h>
#include <pwd.h>   
#include <sys/wait.h>
#include <sys/stat.h>
#include <sys/types.h>
#include "prompt.h"
#include "echo.h"